const LatexCodes = {
    "greek_letters_alpha": "\\alpha",
    "greek_letters_beta": "\\beta",
    "greek_letters_gamma": "\\gamma",
    "greek_letters_delta": "\\delta",
    "greek_letters_epsilon": "\\epsilon",
    "greek_letters_zeta": "\\zeta",
    "greek_letters_eta": "\\eta",
    "greek_letters_theta": "\\theta",
    "greek_letters_iota": "\\iota",
    "greek_letters_kappa": "\\kappa",
    "greek_letters_lambda": "\\lambda",
    "greek_letters_mu": "\\mu",
    "greek_letters_nu": "\\mu",
    "greek_letters_xi": "\\xi",
    "greek_letters_pi": "\\pi",
    "greek_letters_rho": "\\rho",
    "greek_letters_sigma": "\\sigma",
    "greek_letters_tau": "\\tau",
    "greek_letters_upsilon": "\\upsilon",
    "greek_letters_phi": "\\phi",
    "greek_letters_chi": "\\chi",
    "greek_letters_psi": "\\psi",
    "greek_letters_omega": "\\omega",
    "greek_letters_digamma": "\\digamma",
    "greek_letters_varepsilon": "\\varepsilon",
    "greek_letters_varkappa": "\\varkappa",
    "greek_letters_varphi": "\\varphi",
    "greek_letters_varpi": "\\varpi",
    "greek_letters_varrho": "\\varrho",
    "greek_letters_varsigma": "\\varsigma",
    "greek_letters_vartheta": "\\vartheta",
    "greek_letters_Gamma": "\\Gamma",
    "greek_letters_Delta": "\\Delta",
    "greek_letters_Lambda": "\\Lambda",
    "greek_letters_Phi": "\\Phi",
    "greek_letters_Pi": "\\Pi",
    "greek_letters_Psi": "\\Psi",
    "greek_letters_Sigma": "\\Sigma",
    "greek_letters_Theta": "\\Theta",
    "greek_letters_Upsilon": "\\Upsilon",
    "greek_letters_Xi": "\\Xi",
    "greek_letters_Omega": "\\Omega",
    "math_accents_acute": ["\\acute{", "}"],
    "math_accents_grave": ["\\grave{", "}"],
    "math_accents_tilde": ["\\tilde{", "}"],
    "math_accents_bar": ["\\bar{", "}"],
    "math_accents_breve": ["\\breve{", "}"],
    "math_accents_check": ["\\check{", "}"],
    "math_accents_hat": ["\\hat{", "}"],
    "math_accents_vec": ["\\vec{", "}"],
    "math_accents_dot": ["\\dot{", "}"],
    "math_accents_ddot": ["\\ddot{", "}"],
    "math_accents_dddot": ["\\dddot{", "}"],
    "math_accents_mathring": ["\\mathring{", "}"],
    "math_accents_imath": "\\hat{\\imath}",
    "math_accents_jmath": "\\hat{\\jmath}",
    "math_accents_widetilde": ["\\widetilde{", "}"],
    "math_accents_widehat": ["\\widehat{", "}"],

    "notations-003": ["\\overline{", "}"],
    "notations-004": ["\\underline{", "}"],
    "notations-005": ["\\overbrace{", "}"],
    "notations-006": ["\\underbrace{", "}"],
    "notations-007": ["\\overleftarrow{", "}"],
    "notations-008": ["\\underleftarrow{", "}"],
    "notations-009": ["\\overrightarrow{", "}"],
    "notations-010": ["\\underrightarrow{", "}"],
    "notations-011": ["\\overleftrightarrow{", "}"],
    "notations-012": ["\\underleftrightarrow{", "}"],

    "math_set_varnothing": "\\varnothing",
    "math_set_2": "\\mathbb{N}",
    "math_set_3": "\\mathbb{Z}",
    "math_set_5": "\\mathbb{Q}",
    "math_set_6": "\\mathbb{R}",
    "math_set_8": "\\mathbb{C}",
    "math_set_9": "\\mathbb{Z}_n",
    "math_set_10": "\\mathbb{R}^3",
    "math_set_7": "\\mathbb{R}_+",
    "math_set_4": "\\mathbb{Z}_+",
    "function_sin": "\\sin",
    "function_cos": "\\cos",
    "function_tan": "\\tan",
    "function_csc": "\\csc",
    "function_sec": "\\sec",
    "function_cot": "\\cot",
    "function_sinh": "\\sinh",
    "function_cosh": "\\cosh",
    "function_tanh": "\\tanh",
    "function_coth": "\\coth",
    "function_arcsin": "\\arcsin",
    "function_arccos": "\\arccos",
    "function_arctan": "\\arctan",
    "function_exp": "\\exp",
    "function_lg": "\\lg",
    "function_ln": "\\ln",
    "function_log": "\\log",

    "function_lim": "\\lim",
    "function_liminf": "\\liminf",
    "function_limsup": "\\limsup",
    "function_maximum": "\\max",
    "function_minimum": "\\min",
    "function_infinite": "\\infty",
    "function_varinjlim": "\\varinjlim",
    "function_varprojlim": "\\varprojlim",
    "function_varliminf": "\\varliminf",
    "function_varlimsup": "\\varlimsup",

    "function_arg": "\\arg",
    "function_det": "\\det",
    "function_deg": "\\deg",
    "function_dim": "\\dim",
    "function_gcd": "\\gcd",
    "function_hom": "\\hom",
    "function_ker": "\\ker",
    "function_Pr": "\\Pr",
    "function_sup": "\\sup",
    "function_mod": "\\bmod",

    "basic_symbols_001": "\\aleph",
    "basic_symbols_002": "\\ell",
    "basic_symbols_003": "\\partial",
    "basic_symbols_004": "\\Game",
    "basic_symbols_005": "\\beth",
    "basic_symbols_006": "\\eth",
    "basic_symbols_007": "\\wp",
    "basic_symbols_008": "\\Im",
    "basic_symbols_009": "\\daleth",
    "basic_symbols_010": "\\hbar",
    "basic_symbols_011": "\\circledS",
    "basic_symbols_012": "\\Re",
    "basic_symbols_013": "\\gimel",
    "basic_symbols_014": "\\hslash",
    "basic_symbols_015": "\\Bbbk",
    "basic_symbols_016": "\\complement",
    "basic_symbols_017": "\\mho",
    "basic_symbols_018": "\\Finv",
    "basic_symbols_019": "\\mathfrak{c}",


    "math_font_examples_2": ["\\mathbf{", "}"],
    "math_font_examples_3": ["\\mathrm{", "}"],
    "math_font_examples_4": ["\\mathsf{", "}"],
    "math_font_examples_5": ["\\mathit{", "}"],
    "math_font_examples_6": ["\\mathcal{", "}"],
    "math_font_examples_7": ["\\mathbb{", "}"],
    "math_font_examples_8": ["\\mathfrak{", "}"],
}

export { LatexCodes }