const LatexCodes = {
    "greek_letters_alpha": "\\alpha",
    "greek_letters_beta": "\\beta",
    "greek_letters_gamma": "\\gamma",
    "greek_letters_delta": "\\delta",
    "greek_letters_epsilon": "\\epsilon",
    "greek_letters_zeta": "\\zeta",
    "greek_letters_eta": "\\eta",
    "greek_letters_theta": "\\theta",
    "greek_letters_iota": "\\iota",
    "greek_letters_kappa": "\\kappa",
    "greek_letters_lambda": "\\lambda",
    "greek_letters_mu": "\\mu",
    "greek_letters_nu": "\\mu",
    "greek_letters_xi": "\\xi",
    "greek_letters_pi": "\\pi",
    "greek_letters_rho": "\\rho",
    "greek_letters_sigma": "\\sigma",
    "greek_letters_tau": "\\tau",
    "greek_letters_upsilon": "\\upsilon",
    "greek_letters_phi": "\\phi",
    "greek_letters_chi": "\\chi",
    "greek_letters_psi": "\\psi",
    "greek_letters_omega": "\\omega",
    "greek_letters_digamma": "\\digamma",
    "greek_letters_varepsilon": "\\varepsilon",
    "greek_letters_varkappa": "\\varkappa",
    "greek_letters_varphi": "\\varphi",
    "greek_letters_varpi": "\\varpi",
    "greek_letters_varrho": "\\varrho",
    "greek_letters_varsigma": "\\varsigma",
    "greek_letters_vartheta": "\\vartheta",
    "greek_letters_Gamma": "\\Gamma",
    "greek_letters_Delta": "\\Delta",
    "greek_letters_Lambda": "\\Lambda",
    "greek_letters_Phi": "\\Phi",
    "greek_letters_Pi": "\\Pi",
    "greek_letters_Psi": "\\Psi",
    "greek_letters_Sigma": "\\Sigma",
    "greek_letters_Theta": "\\Theta",
    "greek_letters_Upsilon": "\\Upsilon",
    "greek_letters_Xi": "\\Xi",
    "greek_letters_Omega": "\\Omega",
    "math_accents_acute": ["\\acute{", "}"],
    "math_accents_grave": ["\\grave{", "}"],
    "math_accents_tilde": ["\\tilde{", "}"],
    "math_accents_bar": ["\\bar{", "}"],
    "math_accents_breve": ["\\breve{", "}"],
    "math_accents_check": ["\\check{", "}"],
    "math_accents_hat": ["\\hat{", "}"],
    "math_accents_vec": ["\\vec{", "}"],
    "math_accents_dot": ["\\dot{", "}"],
    "math_accents_ddot": ["\\ddot{", "}"],
    "math_accents_dddot": ["\\dddot{", "}"],
    "math_accents_mathring": ["\\mathring{", "}"],
    "math_accents_widetilde": ["\\widetilde{", "}"],
    "math_accents_widehat": ["\\widehat{", "}"],
}